### ISSUE TITLE
Problem between Cordova SDK 8.1 and iOS SDK 9.x

### ISSUE THREAD

**Issue by martinGerez** [blackberry/BlackBerry-Dynamics-Cordova-Samples#14]
Hi, we were having problems between those versions.

The build error was: `GD/sqlite3enc.h not found` at import time.

We fixed that by downgrading the ios SDK.

Is that a known issue?

**Comment by gghangura** [comment]
Hey @martinGerez , 

Please open a BlackBerry Support ticket for this issue. 

Thanks
Gurjit
