### ISSUE TITLE
GDInitializationError

### ISSUE THREAD

**Issue by sanjaybhaskar** [blackberry/BlackBerry-Dynamics-Cordova-Samples#9]
When i run this app in simulator im getting this following error. Can you please help. What is that i'm missing.

> 08-09 20:09:26.267 17156 17156 E AndroidRuntime: com.good.gd.error.GDInitializationError: Each Activity must implement GDStateListener interface if a singleton interface has not been provided to GDAndroid
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at com.good.gd.GDAndroid.activityInit(SourceFile:214)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at com.good.gd.cordova.core.BBDCordovaActivity.onCreate(BBDCordovaActivity.java:22)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at com.good.gd.cordova.core.MainActivity.onCreate(MainActivity.java:16)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7009)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7000)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> 08-09 20:09:26.267 17156 17156 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by JeffinWithYa** [comment]
Hi @sanjaybhaskar , which sample app did you try running?

**Comment by sanjaybhaskar** [comment]
Secure-ICC app

**Comment by JeffinWithYa** [comment]
I was not able to reproduce this issue. Can you confirm for me what version of the Dynamics SDK you are using? Can you also confirm for me what version of Cordova, Ionic, and Node you are using?

**Comment by JeffinWithYa** [comment]
Hi @sanjaybhaskar , following up on this, can you confirm for me what version of the Dynamics SDK you are using? As well as what version of Cordova, Ionic, and Node you are using?
